name: Deploy V2 Big Bang

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Baixa o c√≥digo novo
      uses: actions/checkout@v4

    - name: Conecta no servidor e atualiza
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY_BIG_BANG }}
        port: 3022
        script: |
          cd ~/v2-big-bang
          
          git pull origin main
          
          sudo docker compose up -d --build
          
          sudo docker image prune -f
